version: "3.7"

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mycontacts

  app:
    build: .
    command: ["npm", "run", "start:docker"]
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - /node_modules
    restart: always
    depends_on:
      - db

volumes:
  pgdata: {}
